server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order service
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, 
        - id: supporting service
          uri: http://localhost:8082
          predicates:
            - Path=/deliveries/**, /inventories/**, 
        - id: dashboard
          uri: http://localhost:8083
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order service
          uri: http://orderService:8080
          predicates:
            - Path=/orders/**, 
        - id: supporting service
          uri: http://supportingService:8080
          predicates:
            - Path=/deliveries/**, /inventories/**, 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
